
// 'use client';

// import { useState, useMemo } from 'react';
// import { Header, Breadcrumb } from '@/components/layout';
// import { StudentSelector, TranscriptOptions, TranscriptPreview } from '@/components/transcript';
// import { mockStudents, mockAcademicYears } from '@/data/mock-data';
// import { Student, TranscriptOptions as TranscriptOptionsType, TranscriptData } from '@/types';

// const defaultOptions: TranscriptOptionsType = {
//   program: 'DP',
//   schoolYear: '2023/2024',
//   sessionType: 'May Session',
//   transcriptType: 'official',
//   includePredictedGrades: true,
// };

// export default function GenerateTranscriptPage() {
//   const [selectedStudent, setSelectedStudent] = useState<Student | null>(null);
//   const [transcriptOptions, setTranscriptOptions] = useState<TranscriptOptionsType>(defaultOptions);

//   // Generate transcript data when a student is selected
//   const transcriptData: TranscriptData | null = useMemo(() => {
//     if (!selectedStudent) return null;

//     return {
//       student: selectedStudent,
//       schoolName: 'Lincoln Community School',
//       schoolAddress: {
//         line1: 'PMB CT 354, Cantonment',
//         city: 'Accra',
//         country: 'Ghana',
//         phone: '+233 30 221 8100',
//         web: 'www.lincoln.edu.gh',
//       },
//       academicYears: mockAcademicYears,
//       principalName: 'First and last name',
//       principalTitle: 'Secondary School Principal',
//     };
//   }, [selectedStudent]);

//   const handleGenerate = () => {
//     if (selectedStudent) {
//       console.log('Generating transcript for:', selectedStudent.name);
//       console.log('Options:', transcriptOptions);
//       // Here you would trigger PDF generation
//       alert(`Generating ${transcriptOptions.transcriptType} transcript for ${selectedStudent.name}`);
//     }
//   };

//   return (
//     <div className="min-h-screen bg-gradient-to-br from-slate-100 via-gray-100 to-slate-200">
//       {/* Header */}
//       <Header activeNav="generate-transcript" />
      
//       {/* Main Content Area */}
//       <main className="px-6 py-8">
//         <div className="max-w-7xl mx-auto">
//           {/* Breadcrumb */}
//           <Breadcrumb 
//             items={[
//               { label: 'Dashboard', href: '/dashboard' },
//               { label: 'Generate Transcript', href: null },
//             ]}
//           />
          
//           {/* Page Title */}
//           <h1 className="text-3xl font-bold text-gray-900 mb-8">
//             Generate Official Transcript
//           </h1>
          
//           {/* Content Grid */}
//           <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
//             {/* Left Column - Student Selection & Options */}
//             <div className="space-y-6">
//               {/* Student Selection */}
//               <StudentSelector
//                 students={mockStudents}
//                 selectedStudent={selectedStudent}
//                 onSelectStudent={setSelectedStudent}
//               />
              
//               {/* Transcript Options */}
//               <TranscriptOptions
//                 options={transcriptOptions}
//                 onOptionsChange={setTranscriptOptions}
//                 onGenerate={handleGenerate}
//                 isStudentSelected={selectedStudent !== null}
//               />
//             </div>
            
//             {/* Right Column - Transcript Preview */}
//             <TranscriptPreview data={transcriptData} />
//           </div>
          
//           {/* Footer Info */}
//           <div className="mt-8 flex items-center gap-8 text-sm text-gray-400">
//             <span>Audit Details: -</span>
//             <span>Generated By: Mr. Smith</span>
//           </div>
//         </div>
//       </main>
//     </div>
//   );
// } 


'use client';

import { useState, useEffect, useMemo, useCallback } from 'react';
import { Header, Breadcrumb } from '@/components/layout';
import { StudentSelector, TranscriptOptions, TranscriptPreview } from '@/components/transcript';
import { useStudents, useTranscript } from '@/hooks';
import { 
  Student, 
  TranscriptOptions as TranscriptOptionsType, 
  TranscriptData,
  transformStudent,
  transformTranscript,
} from '@/types';

const defaultOptions: TranscriptOptionsType = {
  program: 'DP',
  schoolYear: '2023/2024',
  sessionType: 'May Session',
  transcriptType: 'official',
  includePredictedGrades: true,
};

export default function GenerateTranscriptPage() {
  const [selectedStudent, setSelectedStudent] = useState<Student | null>(null);
  const [transcriptOptions, setTranscriptOptions] = useState<TranscriptOptionsType>(defaultOptions);

  // Fetch students from API
  const { 
    students: apiStudents, 
    isLoading: studentsLoading, 
    error: studentsError,
    search: searchStudents,
  } = useStudents();

  // Fetch transcript when a student is selected
  const {
    transcript: apiTranscript,
    isLoading: transcriptLoading,
    error: transcriptError,
  } = useTranscript(selectedStudent?.id || null);

  // Transform API students to UI format
  const students = useMemo(() => {
    return apiStudents.map(transformStudent);
  }, [apiStudents]);

  // Transform API transcript to UI format
  const transcriptData: TranscriptData | null = useMemo(() => {
    if (!apiTranscript) return null;
    return transformTranscript(apiTranscript);
  }, [apiTranscript]);

  // Handle student selection
  const handleSelectStudent = useCallback((student: Student) => {
    setSelectedStudent(student);
  }, []);

  // Handle search
  const handleSearch = useCallback((query: string) => {
    searchStudents(query);
  }, [searchStudents]);

  const handleGenerate = () => {
    if (selectedStudent) {
      console.log('Generating transcript for:', selectedStudent.name);
      console.log('Options:', transcriptOptions);
      alert(`Generating ${transcriptOptions.transcriptType} transcript for ${selectedStudent.name}`);
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-100 via-gray-100 to-slate-200">
      {/* Header */}
      <Header activeNav="generate-transcript" />
      
      {/* Main Content Area */}
      <main className="px-6 py-8">
        <div className="max-w-7xl mx-auto">
          {/* Breadcrumb */}
          <Breadcrumb 
            items={[
              { label: 'Dashboard', href: '/dashboard' },
              { label: 'Generate Transcript', href: null },
            ]}
          />
          
          {/* Page Title */}
          <h1 className="text-3xl font-bold text-gray-900 mb-8">
            Generate Official Transcript
          </h1>
          
          {/* Content Grid */}
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
            {/* Left Column - Student Selection & Options */}
            <div className="space-y-6">
              {/* Student Selection */}
              <StudentSelector
                students={students}
                selectedStudent={selectedStudent}
                onSelectStudent={handleSelectStudent}
                isLoading={studentsLoading}
                error={studentsError}
                onSearch={handleSearch}
              />
              
              {/* Transcript Options */}
              <TranscriptOptions
                options={transcriptOptions}
                onOptionsChange={setTranscriptOptions}
                onGenerate={handleGenerate}
                isStudentSelected={selectedStudent !== null}
              />
            </div>
            
            {/* Right Column - Transcript Preview */}
            <TranscriptPreview 
              data={transcriptData}
              isLoading={transcriptLoading}
              error={transcriptError}
            />
          </div>
          
          {/* Footer Info */}
          <div className="mt-8 flex items-center gap-8 text-sm text-gray-400">
            <span>Audit Details: -</span>
            <span>Generated By: Mr. Ed</span>
          </div>
        </div>
      </main>
    </div>
  );
}